[package]
name = "x509_parser"
version = "0.1.0"
edition = "2024_07"

[dependencies]
asn1.workspace = true
der_parser.workspace = true
int_traits.workspace = true
nom.workspace = true
oid_registry.workspace = true
time.workspace = true

[dev-dependencies]
cairo_test.workspace = true
