on:
  push:
    branches:
      - "master"
  pull_request:

name: "Test"
jobs:
  test:
    name: "Run tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Set up PATH"
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Install scarb"
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh -s -- -v 2.12.0

      - name: "Print scarb version"
        run: |
          scarb --version

      - name: "Run tests"
        run: |
          scarb test
